import {
  type ActivityItem,
  type AssetItem,
  type ChartPoint,
  type DashboardMetric,
  type DemandItem,
  type RequestItem,
  type StockItem,
  type TeamMember,
  type StockCategory,
} from "@/types/cpd";

export const dashboardMetrics: DashboardMetric[] = [
  { label: "Demandas abertas", value: "24", delta: "+4 esta semana", tone: "blue" },
  { label: "Solicitacoes pendentes", value: "13", delta: "5 em analise", tone: "amber" },
  { label: "Estoque baixo", value: "7", delta: "3 criticos", tone: "rose" },
  { label: "Equipamentos em manutencao", value: "9", delta: "2 internos", tone: "emerald" },
];

export const monthlyDemandData: ChartPoint[] = [
  { label: "Jan", value: 18 },
  { label: "Fev", value: 22 },
  { label: "Mar", value: 31 },
  { label: "Abr", value: 26 },
  { label: "Mai", value: 38 },
  { label: "Jun", value: 34 },
  { label: "Jul", value: 41 },
];

export const requestByCategoryData: ChartPoint[] = [
  { label: "Equipamentos", value: 24 },
  { label: "Materiais", value: 18 },
  { label: "Pecas", value: 12 },
  { label: "Software", value: 9 },
  { label: "Rede", value: 7 },
];

export const topMaterialsData: ChartPoint[] = [
  { label: "Fonte 500W", value: 14 },
  { label: "SSD 480GB", value: 12 },
  { label: "Memoria DDR4", value: 10 },
  { label: "Mouse Optico", value: 8 },
  { label: "Cabo UTP", value: 6 },
];

export const demandItems: DemandItem[] = [
  {
    id: "dmd-001",
    kind: "internal",
    number: "DEM-2026-0014",
    requester: "Secretaria de Saude",
    sector: "Triagem",
    owner: "Tiago Nunes",
    summary: "Troca de fonte e verificacao de disco em computador do setor.",
    date: "2026-07-16",
    priority: "high",
    status: "waiting_material",
    attachments: 2,
    notes: "Aguardando chegada de fonte compativel.",
    patrimony: "P-10234",
    equipment: "Desktop Dell OptiPlex 7010",
    defect: "Sem partida",
    report: "Relatorio pendente.",
  },
  {
    id: "dmd-002",
    kind: "field",
    number: "DEM-2026-0015",
    requester: "Gabinete",
    sector: "Administrativo",
    owner: "Larissa Souza",
    summary: "Instalacao de impressora e configuracao de rede.",
    date: "2026-07-15",
    priority: "medium",
    status: "in_progress",
    attachments: 1,
    notes: "Equipamento ja retirado para testes.",
    location: "Predio Anexo",
    phoneExtension: "234",
    openedBy: "Marcos Lima",
    openedAt: "2026-07-15T08:10:00",
    report: "Aguardando validacao em campo.",
  },
  {
    id: "dmd-003",
    kind: "internal",
    number: "DEM-2026-0016",
    requester: "Secretaria de Educacao",
    sector: "TI Escolar",
    owner: "Renato Alves",
    summary: "Equipamento sem video e com alerta de temperatura.",
    date: "2026-07-14",
    priority: "urgent",
    status: "open",
    attachments: 3,
    notes: "Necessita analise fisica imediata.",
    patrimony: "P-10921",
    equipment: "Notebook HP EliteBook 840",
    defect: "Sem video e superaquecimento",
    report: "Em aberto.",
  },
  {
    id: "dmd-004",
    kind: "field",
    number: "DEM-2026-0017",
    requester: "Secretaria de Obras",
    sector: "Canteiro",
    owner: "Pedro Henrique",
    summary: "Acesso a sistema e troca de cabo de rede em posto remoto.",
    date: "2026-07-13",
    priority: "medium",
    status: "done",
    attachments: 1,
    notes: "Atendimento finalizado e relatado.",
    location: "Unidade 3",
    phoneExtension: "318",
    openedBy: "Fernanda Costa",
    openedAt: "2026-07-13T09:30:00",
    closedAt: "2026-07-13T11:05:00",
    report: "Problema resolvido no local.",
  },
];

export const requestItems: RequestItem[] = [
  {
    id: "req-001",
    number: "SOL-2026-0031",
    category: "Materiais",
    item: "Cabos HDMI",
    quantity: 20,
    requester: "Marcos Lima",
    justification: "Reposicao do estoque para manutencao preventiva.",
    notes: "Compra recorrente.",
    priority: "medium",
    status: "review",
  },
  {
    id: "req-002",
    number: "SOL-2026-0032",
    category: "Equipamentos",
    item: "Notebooks para atendimento",
    quantity: 4,
    requester: "Fernanda Costa",
    justification: "Substituicao dos terminais obsoletos da recepcao.",
    notes: "Requer aprovacao da coordenacao.",
    priority: "high",
    status: "approved",
  },
  {
    id: "req-003",
    number: "SOL-2026-0033",
    category: "Pecas",
    item: "Kit memoria DDR4 8GB",
    quantity: 6,
    requester: "Pedro Henrique",
    justification: "Manter equipamentos da rede interna em operacao.",
    notes: "Prioridade alta para os postos de atendimento.",
    priority: "urgent",
    status: "buying",
  },
];

export const stockCategories: StockCategory[] = [
  {
    id: "cat-001",
    name: "Computadores",
    description: "Componentes e peças para computadores.",
  },
  {
    id: "cat-002",
    name: "Rede",
    description: "Equipamentos e materiais de rede.",
  },
  {
    id: "cat-003",
    name: "Periféricos",
    description: "Mouse, teclado e acessórios.",
  },
];

export const stockItems: StockItem[] = [
  {
    id: "stk-001",
    name: "SSD 240GB",
    specification: "SSD SATA 2.5 polegadas",
    type: "Armazenamento",
    categoryId: "cat-001",
    quantity: 4,
  },
  {
    id: "stk-002",
    name: "Fonte ATX 500W",
    specification: "Fonte 500W padrão ATX",
    type: "Energia",
    categoryId: "cat-001",
    quantity: 12,
  },
  {
    id: "stk-003",
    name: "Mouse USB",
    specification: "Mouse óptico USB 2.0",
    type: "Periféricos",
    categoryId: "cat-003",
    quantity: 28,
  },
];

export const assetItems: AssetItem[] = [
  {
    id: "ast-001",
    patrimonyNumber: "P-10234",
    equipment: "Desktop",
    model: "OptiPlex 7010",
    brand: "Dell",
    serialNumber: "CN-0XK21J-74261",
    secretary: "Secretaria de Saude",
    responsible: "Tiago Nunes",
    condition: "active",
    notes: "Operacional e vinculado ao atendimento de triagem.",
  },
  {
    id: "ast-002",
    patrimonyNumber: "P-10444",
    equipment: "Desktop",
    model: "ThinkCentre M70q",
    brand: "Lenovo",
    serialNumber: "R90S12X",
    secretary: "Gabinete",
    responsible: "Larissa Souza",
    condition: "maintenance",
    notes: "Aguardando reinstalacao apos manutencao.",
  },
  {
    id: "ast-003",
    patrimonyNumber: "P-10921",
    equipment: "Notebook",
    model: "EliteBook 840",
    brand: "HP",
    serialNumber: "5CD3421",
    secretary: "Coordenacao CPD",
    responsible: "Renato Alves",
    condition: "reserved",
    notes: "Reservado para atendimento externo.",
  },
];

export const activities: ActivityItem[] = [
  {
    id: "act-001",
    actor: "Tiago Nunes",
    action: "Atualizou status da demanda",
    target: "DEM-2026-0014",
    previousValue: "Em atendimento",
    currentValue: "Aguardando material",
    timestamp: "2026-07-17T08:20:00",
  },
  {
    id: "act-002",
    actor: "Larissa Souza",
    action: "Aprovou solicitacao",
    target: "SOL-2026-0032",
    previousValue: "Em analise",
    currentValue: "Aprovada",
    timestamp: "2026-07-17T09:45:00",
  },
  {
    id: "act-003",
    actor: "Pedro Henrique",
    action: "Registrou entrada no estoque",
    target: "EST-0012",
    previousValue: "10 unidades",
    currentValue: "12 unidades",
    timestamp: "2026-07-17T10:13:00",
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: "usr-001",
    name: "Vinicius Oliveira",
    role: "administrator",
    active: true,
    email: "vinicius@prefeitura.local",
    lastAccess: "2026-07-17T10:12:00",
  },
  {
    id: "usr-002",
    name: "Larissa Souza",
    role: "coordinator",
    active: true,
    email: "larissa@prefeitura.local",
    lastAccess: "2026-07-17T09:41:00",
  },
  {
    id: "usr-003",
    name: "Pedro Henrique",
    role: "technician",
    active: true,
    email: "pedro@prefeitura.local",
    lastAccess: "2026-07-16T17:35:00",
  },
];
